### ISSUE TITLE
Present the list of options for discoverability

### ISSUE THREAD

**Issue by alexherbo2** [launchlet/launchlet#1]
When Launchlet starts, present the list of options for discoverability.

**Comment by alexherbo2** [comment]
The use case is to present an interactive help on <kbd>F1</kbd> for [Krabby].

[Krabby]: https://github.com/alexherbo2/krabby

**Comment by rosano** [comment]
I assume this is regarding Commit mode? I thought about this a few times but I think it is a usability problem to present an unbound quantity of items at once, and it also can degrade performance if the number is large - to say another way, I think it makes sense to present 'everything' only if there is a small number of items (let's say max 10-12). I will close for now and re-post here if I think start thinking differently about this.

Here's how I accomplish the same thing with Preview mode:

```javascript
let selectedItem;

Launchlet.LCHSingletonCreate({
  LCHOptionRecipes: [{
    LCHRecipeName: 'alfa',
    LCHRecipeCallback () {
      selectedItem = 'bravo';
    },
  }, {
    LCHRecipeName: 'charlie',
    LCHRecipeCallback () {
      selectedItem = 'delta';
    },
  }],
  LCHOptionCompletionHandler () {
    console.log(selectedItem);
  },
  LCHOptionMode: Launchlet.LCHModePreview,
});
```

**Comment by alexherbo2** [comment]
Preview runs the commands on selection, which is not what I want for Krabby.
